version: '3'

services:
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600

  book-service:
    image: dmcelligott/book-service
    links:
      - consul
      - book-recommendation-service

  book-recommendation-service:
    image: dmcelligott/book-recommendation-service
    links:
      - consul

  gateway:
    image: dmcelligott/gateway
    ports:
      - 8080:8080
    links:
      - consul

  hystrix-dashboard:
    image: dmcelligott/hystrix-dashboard
    ports:
      - 8092:8092
    links:
      - consul
      - book-recommendation-service
      - book-service
      - gateway