version: '3'

services:
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600

  book-service:
    image: dmcelligott/book-service
    links:
      - consul
      - jaeger
    environment:
      - JAEGER_AGENT_HOST=jaeger

  gateway:
    image: dmcelligott/gateway
    ports:
      - 8080:8080
    links:
      - consul
      - jaeger
    environment:
      - JAEGER_AGENT_HOST=jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
     - 5775:5775/udp
     - 6831:6831/udp
     - 6832:6832/udp
     - 5778:5778
     - 16686:16686
     - 14268:14268
     - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411