version: '3'

services:
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600

  book-service:
    image: dmcelligott/book-service
    ports:
      - 8090:8090
    links:
      - consul

  gateway:
    image: dmcelligott/gateway
    ports:
      - 8080:8080
    links:
      - consul