spring:
  application:
    name:
      gateway
  cloud:
    consul:
      enabled: true
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
zuul:
  ignoredServices: '*'
  routes:
    books:
      path: /books/**
      serviceId: book-service

server:
  port: 8080

management:
  security:
    enabled: false

logging:
  level:
    io.opentracing: trace
    org:
      springframework:
        cloud:
          netflix: debug

---
spring:
  profiles: docker
  application:
    name: gateway
  cloud:
    consul:
      enabled: true
      discovery:
        prefer-ip-address: true
      host: consul
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true

zuul:
  ignoredServices: '*'
  routes:
    books:
      path: /books/**
      serviceId: book-service

server:
  port: 8080

management:
  security:
    enabled: false