spring:
  application:
    name:
      book-service
  cloud:
    consul:
      enabled: false

---

server:
  port: 8090

spring:
  profiles: local
  cloud:
    consul:
      enabled: true
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
management:
  security:
    enabled: false

---
server:
  port: 8090

spring:
  profiles: docker
  cloud:
    consul:
      enabled: true
      discovery:
        prefer-ip-address: true
      host: consul
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
management:
  security:
    enabled: false

---

spring:
  profiles: unit
  cloud:
    consul:
        enabled: false
  logging:
    level:
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  security:
    enabled: false

