spring:
  application:
    name:
      book-service

---

server:
  port: 8090

spring:
  profiles: local
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
management:
  health:
    consul:
      enabled: false
  security:
    enabled: false

---
server:
  port: 8090

spring:
  profiles: docker
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: consul
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true
management:
  health:
    consul:
      enabled: false
  security:
    enabled: false

---

spring:
  profiles: unit
  cloud:
    consul:
        enabled: false

management:
  health:
    consul:
      enabled: false
  security:
    enabled: false